spring:
 cloud:
  gateway:
    routes:
        - id: ServiceA
          uri: lb://ServiceA
          predicates:
           - Path=/A/**
        - id: ServiceB
          uri: lb://ServiceB
          predicates:
           - Path=/B/**    